### ISSUE TITLE
引号未闭合，是插件提示，还是 zhlint 原因？

### ISSUE THREAD

**Issue by ygqygq2** [stackia/eslint-plugin-zhlint#3]
https://github.com/Jinjiang/zhlint/issues/107

![image](https://github.com/stackia/eslint-plugin-zhlint/assets/17672440/1801c677-f3a5-4243-87ba-1599ddfec9a8)

**Comment by stackia** [comment]
插件对于每一行 `//` 注释是分别独立调用 zhlint，因为这里 `{` `}` 跨行了，所以 zhlint 没能配对
研究了下比较难搞，现在只有用 `/* ... */` 这种多行块注释，才能整体交给 zhlint 一起处理

**Comment by ygqygq2** [comment]
明白了，谢谢。暂时先不管它了。我只是设置提示，不碍事。
