### ISSUE TITLE
有没有兴趣作为 zhlint 官方插件一起维护？

### ISSUE THREAD

**Issue by Jinjiang** [stackia/eslint-plugin-zhlint#4]
Hi 我是 zhlint 的作者，很偶然的机会看到这个插件，非常棒！如果有兴趣的话，可以 transfer 到 https://github.com/zhlint-project 这个 org 我们一起维护。谢谢🙏

**Comment by stackia** [comment]
很高兴看到 zhlint 开发最近又活跃了起来，我很乐意 transfer 到 zhlint-project 下一起维护！
对应的 npm package 我已经邀请你作为 maintainer。
